[workspace]
members = [
    "crates/SYNAPSE_-app",
    "crates/SYNAPSE_-renderer",
    "crates/SYNAPSE_-ui",
    "crates/SYNAPSE_-config",
    "crates/SYNAPSE_-suggest",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["SYNAPSE_ Team"]
repository = "https://github.com/isradev-git/synapse_"
homepage = "https://github.com/isradev-git/synapse_"
description = "A cyberpunk GPU-accelerated terminal emulator"

[workspace.dependencies]
# Forzar rustix 0.38 con std para que OwnedFd == std::os::fd::OwnedFd.
# Esto unifica el tipo con rustix-openpty y arregla el build de alacritty_terminal.
rustix = { version = "=0.38.44", features = ["std", "process"] }
winit = "0.30"
wgpu = "22"
fontdue = "0.9"
alacritty_terminal = "0.24"
portable-pty = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
arboard = "3"
tracing = "0.1"
tracing-subscriber = "0.3"
bitflags = "2"
clap = { version = "4", features = ["derive"] }
pollster = "0.3"
bytemuck = { version = "1", features = ["derive"] }
rustybuzz = "0.14"
base64 = "0.22"
png = "0.17"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "bmp"] }
ttf-parser = "0.25"

[profile.dist]
inherits = "release"
lto = "thin"
