[package]
name = "Luna-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Luna terminal emulator — binary entry point"

[[bin]]
name = "luna"
path = "src/main.rs"

[dependencies]
Luna-terminal = { path = "../Luna-terminal" }
Luna-renderer = { path = "../Luna-renderer" }
Luna-ui = { path = "../Luna-ui" }
Luna-config = { path = "../Luna-config" }

 winit = { workspace = true }
wgpu = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
arboard = { workspace = true }
