[package]
name = "SYNAPSE_-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
name = "synapse_ui"
path = "src/lib.rs"

[dependencies]
tracing = { workspace = true }
alacritty_terminal = { workspace = true }
portable-pty = { workspace = true }
SYNAPSE_-renderer = { path = "../SYNAPSE_-renderer" }
winit = { workspace = true }
