[package]
name = "SYNAPSE_-app"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "SYNAPSE_ terminal emulator — binary entry point"

[[bin]]
name = "synapse_"
path = "src/main.rs"

[dependencies]
SYNAPSE_-renderer = { path = "../SYNAPSE_-renderer" }
SYNAPSE_-ui = { path = "../SYNAPSE_-ui" }
SYNAPSE_-config = { path = "../SYNAPSE_-config" }
SYNAPSE_-suggest = { path = "../SYNAPSE_-suggest" }
alacritty_terminal = { workspace = true }
rustix = { workspace = true }
portable-pty = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
arboard = { workspace = true }
base64 = { workspace = true }
png = { workspace = true }
