/// Tiered static completions: (command_string, initial_count).
/// Higher counts give more-common commands better ranking out of the box.
/// Once user history accumulates, it naturally overtakes these seeds.
pub const BUILTINS_TIERED: &[(&str, u32)] = &[
    // ── Tier 3 (count=5): ubiquitous commands ─────────────────────────────────
    ("ls", 5),
    ("ls -la", 5),
    ("ls -lh", 5),
    ("cd ..", 5),
    ("pwd", 5),
    ("cat", 5),
    ("less", 5),
    ("head", 5),
    ("tail", 5),
    ("tail -f", 5),
    ("echo", 5),
    ("touch", 5),
    ("mkdir", 5),
    ("mkdir -p", 5),
    ("rm", 5),
    ("rm -rf", 5),
    ("cp", 5),
    ("cp -r", 5),
    ("mv", 5),
    ("chmod +x", 5),
    ("which", 5),
    ("man", 5),
    ("sudo", 5),
    ("whoami", 5),
    ("grep", 5),
    ("grep -r", 5),
    ("grep -rn", 5),
    ("grep -i", 5),
    ("find . -name", 5),
    ("find . -type f", 5),
    ("awk", 5),
    ("awk '{print $1}'", 5),
    ("sed", 5),
    ("sort", 5),
    ("wc -l", 5),
    ("tar", 5),
    ("tar -czf", 5),
    ("tar -xzf", 5),
    ("gzip", 5),
    ("gunzip", 5),
    ("zip", 5),
    ("unzip", 5),
    ("du -sh", 5),
    ("df -h", 5),
    ("free -h", 5),
    ("ps aux", 5),
    ("top", 5),
    ("htop", 5),
    ("kill", 5),
    ("kill -9", 5),
    ("history", 5),
    ("history | grep", 5),
    ("env", 5),
    ("export", 5),
    ("source", 5),
    ("alias", 5),
    ("date", 5),
    ("vim", 5),
    ("nano", 5),
    ("python3", 5),
    ("pip install", 5),
    ("node", 5),
    ("npm install", 5),
    ("npm run", 5),
    ("npm run dev", 5),
    ("apt update", 5),
    ("apt upgrade", 5),
    ("apt install", 5),
    ("ssh", 5),
    ("curl", 5),
    ("wget", 5),
    ("make", 5),
    ("cd", 5),
    // ── Git (tier 3) ──────────────────────────────────────────────────────────
    ("git status", 5),
    ("git log", 5),
    ("git log --oneline", 5),
    ("git diff", 5),
    ("git add", 5),
    ("git add .", 5),
    ("git add -p", 5),
    ("git commit", 5),
    ("git commit -m", 5),
    ("git push", 5),
    ("git push origin", 5),
    ("git push origin main", 5),
    ("git pull", 5),
    ("git pull --rebase", 5),
    ("git fetch", 5),
    ("git branch", 5),
    ("git branch -a", 5),
    ("git checkout", 5),
    ("git checkout -b", 5),
    ("git checkout main", 5),
    ("git switch", 5),
    ("git merge", 5),
    ("git rebase", 5),
    ("git stash", 5),
    ("git stash pop", 5),
    ("git reset", 5),
    ("git reset HEAD", 5),
    ("git remote -v", 5),
    ("git init", 5),
    ("git clone", 5),
    ("git blame", 5),
    ("git show", 5),
    // ── Cargo / Rust (tier 3) ─────────────────────────────────────────────────
    ("cargo build", 5),
    ("cargo build --release", 5),
    ("cargo run", 5),
    ("cargo test", 5),
    ("cargo test -p", 5),
    ("cargo test -- --nocapture", 5),
    ("cargo check", 5),
    ("cargo clippy", 5),
    ("cargo clippy --workspace --all-targets -- -D warnings", 5),
    ("cargo fmt", 5),
    ("cargo fmt --all", 5),
    ("cargo doc", 5),
    ("cargo add", 5),
    ("cargo update", 5),
    ("cargo clean", 5),
    ("cargo tree", 5),
    ("rustup update", 5),
    ("rustup component add", 5),
    ("rustc --version", 5),
    // ── Docker (tier 3) ──────────────────────────────────────────────────────
    ("docker ps", 5),
    ("docker ps -a", 5),
    ("docker images", 5),
    ("docker build", 5),
    ("docker run", 5),
    ("docker run -it", 5),
    ("docker run --rm", 5),
    ("docker exec", 5),
    ("docker exec -it", 5),
    ("docker stop", 5),
    ("docker rm", 5),
    ("docker pull", 5),
    ("docker logs", 5),
    ("docker system prune", 5),
    ("docker compose up", 5),
    ("docker compose up -d", 5),
    ("docker compose down", 5),
    ("docker compose build", 5),
    ("docker compose logs", 5),
    // ── Tier 2 (count=3): common but situational ──────────────────────────────
    ("ls -1", 3),
    ("ls -R", 3),
    ("rmdir", 3),
    ("rm -i", 3),
    ("mv -i", 3),
    ("ln -s", 3),
    ("chmod", 3),
    ("chmod 755", 3),
    ("chmod 644", 3),
    ("chown", 3),
    ("stat", 3),
    ("file", 3),
    ("whereis", 3),
    ("type", 3),
    ("find . -type d", 3),
    ("find . -mtime", 3),
    ("find . -type f -delete", 3),
    ("grep -v", 3),
    ("grep -l", 3),
    ("grep -E", 3),
    ("sed -i", 3),
    ("sed 's///g'", 3),
    ("sort -n", 3),
    ("sort -r", 3),
    ("sort -u", 3),
    ("uniq", 3),
    ("uniq -c", 3),
    ("wc", 3),
    ("wc -w", 3),
    ("cut -d", 3),
    ("xargs", 3),
    ("diff", 3),
    ("diff -u", 3),
    ("patch", 3),
    ("tar -tzf", 3),
    ("du -sh *", 3),
    ("ps aux | grep", 3),
    ("killall", 3),
    ("pkill", 3),
    ("pgrep", 3),
    ("jobs", 3),
    ("fg", 3),
    ("bg", 3),
    ("tmux", 3),
    ("tmux new-session", 3),
    ("tmux attach", 3),
    ("info", 3),
    ("time", 3),
    ("watch", 3),
    ("crontab -e", 3),
    ("crontab -l", 3),
    ("sudo su", 3),
    ("su -", 3),
    ("id", 3),
    ("groups", 3),
    ("mount", 3),
    ("umount", 3),
    ("lsblk", 3),
    ("lsof", 3),
    ("dmesg", 3),
    ("journalctl", 3),
    ("journalctl -f", 3),
    ("journalctl -u", 3),
    ("systemctl", 3),
    ("systemctl start", 3),
    ("systemctl stop", 3),
    ("systemctl restart", 3),
    ("systemctl status", 3),
    ("systemctl enable", 3),
    ("systemctl disable", 3),
    ("uname -a", 3),
    ("lscpu", 3),
    ("uptime", 3),
    ("hostname", 3),
    ("ip addr", 3),
    ("ip route", 3),
    ("ifconfig", 3),
    ("ping", 3),
    ("ping -c 4", 3),
    ("netstat -tulpn", 3),
    ("ss -tulpn", 3),
    ("curl -X POST", 3),
    ("curl -H", 3),
    ("curl -o", 3),
    ("curl -L", 3),
    ("wget -O", 3),
    ("ssh-keygen", 3),
    ("ssh-copy-id", 3),
    ("scp", 3),
    ("rsync", 3),
    ("rsync -avz", 3),
    ("nc", 3),
    ("nmap", 3),
    ("emacs", 3),
    ("python3 -m", 3),
    ("python3 -c", 3),
    ("pip3 install", 3),
    ("pip3 install -r requirements.txt", 3),
    ("npm run build", 3),
    ("npm run test", 3),
    ("npx", 3),
    ("apt remove", 3),
    ("apt autoremove", 3),
    ("apt-get update", 3),
    ("apt-get install", 3),
    ("make clean", 3),
    ("make install", 3),
    ("gcc -o", 3),
    ("g++ -o", 3),
    ("clang", 3),
    // ── Git (tier 2) ──────────────────────────────────────────────────────────
    ("git status --short", 3),
    ("git log --oneline --graph", 3),
    ("git log --oneline --graph --all", 3),
    ("git diff --staged", 3),
    ("git diff HEAD", 3),
    ("git commit -am", 3),
    ("git commit --amend", 3),
    ("git push --force-with-lease", 3),
    ("git fetch --all", 3),
    ("git fetch --prune", 3),
    ("git branch -d", 3),
    ("git branch -D", 3),
    ("git switch -c", 3),
    ("git merge --no-ff", 3),
    ("git rebase -i HEAD~", 3),
    ("git rebase origin/main", 3),
    ("git stash list", 3),
    ("git stash drop", 3),
    ("git reset --soft HEAD~1", 3),
    ("git reset --hard HEAD~1", 3),
    ("git clean -fd", 3),
    ("git remote", 3),
    ("git remote add origin", 3),
    ("git tag", 3),
    ("git tag -a", 3),
    ("git cherry-pick", 3),
    ("git bisect start", 3),
    ("git submodule update --init", 3),
    ("git worktree", 3),
    // ── Cargo / Rust (tier 2) ─────────────────────────────────────────────────
    ("cargo build -p", 3),
    ("cargo run --release", 3),
    ("cargo run -p", 3),
    ("cargo test --workspace", 3),
    ("cargo check --workspace", 3),
    ("cargo fmt --all -- --check", 3),
    ("cargo doc --open", 3),
    ("cargo remove", 3),
    ("cargo publish", 3),
    ("cargo bench", 3),
    ("cargo new", 3),
    ("cargo init", 3),
    ("cargo audit", 3),
    ("cargo outdated", 3),
    ("cargo expand", 3),
    ("rustup show", 3),
    ("rustup target add", 3),
    ("rustup component add rust-analyzer", 3),
    ("rustup toolchain install", 3),
    ("rustfmt", 3),
    // ── Docker (tier 2) ──────────────────────────────────────────────────────
    ("docker build -t", 3),
    ("docker build -f", 3),
    ("docker run -d", 3),
    ("docker run -p", 3),
    ("docker run -v", 3),
    ("docker start", 3),
    ("docker restart", 3),
    ("docker rm -f", 3),
    ("docker rmi", 3),
    ("docker push", 3),
    ("docker logs -f", 3),
    ("docker inspect", 3),
    ("docker network ls", 3),
    ("docker volume ls", 3),
    ("docker compose logs -f", 3),
    ("docker compose ps", 3),
    ("docker compose exec", 3),
    // ── Tier 1 (count=1): rare / specialized ──────────────────────────────────
    ("tail -n 100", 1),
    ("printf", 1),
    ("cut -f", 1),
    ("tr", 1),
    ("tee", 1),
    ("nohup", 1),
    ("screen", 1),
    ("cron", 1),
    ("strace", 1),
    ("ltrace", 1),
    ("lsmem", 1),
    ("cmake ..", 1),
    ("cmake -DCMAKE_BUILD_TYPE=Release", 1),
    ("dpkg -i", 1),
    ("dpkg -l", 1),
    // ── Git (tier 1) ──────────────────────────────────────────────────────────
    ("git bisect good", 1),
    ("git bisect bad", 1),
    // ── Docker (tier 1) ──────────────────────────────────────────────────────
    ("docker compose events", 1),
    ("docker compose watch", 1),
];
