/// Static database of common commands seeded into the trie at startup.
/// All entries use count=1 so user history always wins in ranking.
/// Covers: Unix core, Git, Cargo/Rust, Docker.
pub const BUILTINS: &[&str] = &[
    // ── Unix core ────────────────────────────────────────────────────────────
    "ls",
    "ls -la",
    "ls -lh",
    "ls -1",
    "ls -R",
    "cd ..",
    "pwd",
    "cat",
    "less",
    "more",
    "head",
    "tail",
    "tail -f",
    "tail -n 100",
    "echo",
    "printf",
    "touch",
    "mkdir",
    "mkdir -p",
    "rmdir",
    "rm",
    "rm -rf",
    "rm -i",
    "cp",
    "cp -r",
    "mv",
    "ln -s",
    "chmod",
    "chmod +x",
    "chmod 755",
    "chmod 644",
    "chown",
    "stat",
    "file",
    "which",
    "whereis",
    "type",
    "find . -name",
    "find . -type f",
    "find . -type d",
    "find . -mtime",
    "grep",
    "grep -r",
    "grep -rn",
    "grep -i",
    "grep -v",
    "grep -l",
    "grep -E",
    "awk",
    "awk '{print $1}'",
    "sed",
    "sed -i",
    "sed 's///g'",
    "sort",
    "sort -n",
    "sort -r",
    "sort -u",
    "uniq",
    "uniq -c",
    "wc",
    "wc -l",
    "wc -w",
    "cut -d",
    "cut -f",
    "tr",
    "tee",
    "xargs",
    "diff",
    "diff -u",
    "patch",
    "tar",
    "tar -czf",
    "tar -xzf",
    "tar -tzf",
    "zip",
    "unzip",
    "gzip",
    "gunzip",
    "du -sh",
    "du -sh *",
    "df -h",
    "free -h",
    "ps aux",
    "ps aux | grep",
    "top",
    "htop",
    "kill",
    "kill -9",
    "killall",
    "pkill",
    "pgrep",
    "jobs",
    "fg",
    "bg",
    "nohup",
    "screen",
    "tmux",
    "tmux new-session",
    "tmux attach",
    "history",
    "history | grep",
    "env",
    "export",
    "source",
    "alias",
    "man",
    "info",
    "date",
    "time",
    "watch",
    "cron",
    "crontab -e",
    "crontab -l",
    "sudo",
    "sudo su",
    "su -",
    "whoami",
    "id",
    "groups",
    "chmod",
    "chown",
    "mount",
    "umount",
    "lsblk",
    "lsof",
    "strace",
    "ltrace",
    "dmesg",
    "journalctl",
    "journalctl -f",
    "journalctl -u",
    "systemctl",
    "systemctl start",
    "systemctl stop",
    "systemctl restart",
    "systemctl status",
    "systemctl enable",
    "systemctl disable",
    "uname -a",
    "lscpu",
    "lsmem",
    "uptime",
    "hostname",
    "ip addr",
    "ip route",
    "ifconfig",
    "ping",
    "ping -c 4",
    "netstat -tulpn",
    "ss -tulpn",
    "curl",
    "curl -X POST",
    "curl -H",
    "curl -o",
    "curl -L",
    "wget",
    "wget -O",
    "ssh",
    "ssh-keygen",
    "ssh-copy-id",
    "scp",
    "rsync",
    "rsync -avz",
    "nc",
    "nmap",
    "vim",
    "nano",
    "emacs",
    "python3",
    "python3 -m",
    "python3 -c",
    "pip install",
    "pip3 install",
    "pip3 install -r requirements.txt",
    "node",
    "npm install",
    "npm run",
    "npm run dev",
    "npm run build",
    "npm run test",
    "npx",
    "apt update",
    "apt upgrade",
    "apt install",
    "apt remove",
    "apt autoremove",
    "apt-get update",
    "apt-get install",
    "dpkg -i",
    "dpkg -l",
    "make",
    "make clean",
    "make install",
    "cmake ..",
    "cmake -DCMAKE_BUILD_TYPE=Release",
    "gcc -o",
    "g++ -o",
    "clang",
    // ── Git ──────────────────────────────────────────────────────────────────
    "git status",
    "git status --short",
    "git log",
    "git log --oneline",
    "git log --oneline --graph",
    "git log --oneline --graph --all",
    "git diff",
    "git diff --staged",
    "git diff HEAD",
    "git add",
    "git add .",
    "git add -p",
    "git commit",
    "git commit -m",
    "git commit -am",
    "git commit --amend",
    "git push",
    "git push origin",
    "git push origin main",
    "git push --force-with-lease",
    "git pull",
    "git pull --rebase",
    "git fetch",
    "git fetch --all",
    "git fetch --prune",
    "git branch",
    "git branch -a",
    "git branch -d",
    "git branch -D",
    "git checkout",
    "git checkout -b",
    "git checkout main",
    "git switch",
    "git switch -c",
    "git merge",
    "git merge --no-ff",
    "git rebase",
    "git rebase -i HEAD~",
    "git rebase origin/main",
    "git stash",
    "git stash pop",
    "git stash list",
    "git stash drop",
    "git reset",
    "git reset HEAD",
    "git reset --soft HEAD~1",
    "git reset --hard HEAD~1",
    "git clean -fd",
    "git remote",
    "git remote -v",
    "git remote add origin",
    "git tag",
    "git tag -a",
    "git cherry-pick",
    "git bisect",
    "git blame",
    "git show",
    "git init",
    "git clone",
    "git submodule update --init",
    "git worktree",
    // ── Cargo / Rust ─────────────────────────────────────────────────────────
    "cargo build",
    "cargo build --release",
    "cargo build -p",
    "cargo run",
    "cargo run --release",
    "cargo run -p",
    "cargo test",
    "cargo test --workspace",
    "cargo test -p",
    "cargo test -- --nocapture",
    "cargo check",
    "cargo check --workspace",
    "cargo clippy",
    "cargo clippy --workspace --all-targets -- -D warnings",
    "cargo fmt",
    "cargo fmt --all",
    "cargo fmt --all -- --check",
    "cargo doc",
    "cargo doc --open",
    "cargo add",
    "cargo remove",
    "cargo update",
    "cargo clean",
    "cargo publish",
    "cargo bench",
    "cargo new",
    "cargo init",
    "cargo tree",
    "cargo audit",
    "cargo outdated",
    "cargo expand",
    "rustup update",
    "rustup show",
    "rustup target add",
    "rustup component add",
    "rustup component add rust-analyzer",
    "rustup toolchain install",
    "rustc --version",
    "rustfmt",
    // ── Docker ───────────────────────────────────────────────────────────────
    "docker ps",
    "docker ps -a",
    "docker images",
    "docker build",
    "docker build -t",
    "docker build -f",
    "docker run",
    "docker run -it",
    "docker run -d",
    "docker run --rm",
    "docker run -p",
    "docker run -v",
    "docker exec",
    "docker exec -it",
    "docker stop",
    "docker start",
    "docker restart",
    "docker rm",
    "docker rm -f",
    "docker rmi",
    "docker pull",
    "docker push",
    "docker logs",
    "docker logs -f",
    "docker inspect",
    "docker network ls",
    "docker volume ls",
    "docker system prune",
    "docker compose up",
    "docker compose up -d",
    "docker compose down",
    "docker compose build",
    "docker compose logs",
    "docker compose logs -f",
    "docker compose ps",
    "docker compose exec",
];
